FILTER_DIPLOMACY_TYPE_ITEMS = {
    {"gui.all"},
    {"ally"},
    {"neutral"},
    {"enemy"}
}
FILTER_DIPLOMACY_TYPE_ALL = 1
FILTER_DIPLOMACY_TYPE_ALLY = 2
FILTER_DIPLOMACY_TYPE_NEUTRAL = 3
FILTER_DIPLOMACY_TYPE_ENEMY = 4